# @Author: sunshine
# @Date:   2017-11-24T16:25:47+08:00
# @Email:  guang334419520@126.com
# @Filename: Makefile
# @Last modified by:   sunshine
# @Last modified time: 2017-11-24T16:28:33+08:00

daytimetcpcli: daytimetcpcli.c
	gcc -g -Wall -o $@ $< -L ../ -lunp
